#!/usr/bin/env bash
set -euo pipefail
SYNC_DIR="/opt/bbfs-github-sync"
REPORT_DIR="$SYNC_DIR/reports"
REPORT_FILE="$REPORT_DIR/audit_inactive_to_active_mapping.txt"
STAMP="$(date '+%Y-%m-%d %H:%M:%S %Z')"
mkdir -p "$REPORT_DIR"
{
  echo "AUDIT MAPPING HISTORY INACTIVE KE MARKET AKTIF"
  echo "Generated: $STAMP"
  echo "Mode: READ ONLY - tidak mengubah database"
  echo
  echo "=== 1. CANDIDATE MAPPING INACTIVE 1000+ -> ACTIVE ==="
  sudo -u postgres psql -d bbfs_production -c "WITH inactive AS (SELECT m.id old_id,m.code old_code,m.name old_name,COUNT(r.id) total_old,MIN(r.draw_date) old_awal,MAX(r.draw_date) old_akhir FROM markets m JOIN result_draws r ON r.market_id=m.id WHERE COALESCE(m.is_active,FALSE)=FALSE GROUP BY m.id,m.code,m.name HAVING COUNT(r.id)>=1000), cand AS (SELECT *, CASE WHEN old_code='sgp-singapore' THEN 'singapore' WHEN old_code='chinapools' THEN 'china' WHEN old_code='magnum-cambodia' THEN 'cambodia' WHEN old_code='hongkong-lotto' THEN 'hongkong' WHEN old_code='sydney-lotto' THEN 'sydney' WHEN old_code LIKE 'toto-macau-%' THEN replace(old_code,'toto-macau-','totomacau-') WHEN old_code LIKE 'new-york-%' THEN replace(old_code,'new-york-','newyork-') WHEN old_code LIKE 'new-jersey-%' THEN replace(old_code,'new-jersey-','newjersey-') WHEN old_code LIKE 'north-carolina-%' THEN replace(old_code,'north-carolina-','carolina-') WHEN old_code LIKE 'washington-dc-%' THEN replace(old_code,'washington-dc-','washington-') ELSE old_code END AS step1_code FROM inactive), cand2 AS (SELECT *, replace(replace(replace(step1_code,'-evening','-eve'),'-midday','-mid'),'-morning','-mor') AS candidate_active_code FROM cand), resolved AS (SELECT c.*, m.id new_id,m.code new_code,m.name new_name FROM cand2 c LEFT JOIN markets m ON m.code=c.candidate_active_code AND m.is_active=TRUE) SELECT old_code,old_name,total_old,old_awal,old_akhir,candidate_active_code,COALESCE(new_code,'NO_ACTIVE_MATCH') AS active_code,COALESCE(new_name,'NO_ACTIVE_MATCH') AS active_name FROM resolved ORDER BY active_code,old_code;"
  echo
  echo "=== 2. CANDIDATE MATCH + INSERT/OVERLAP SUMMARY ==="
  sudo -u postgres psql -d bbfs_production -c "WITH inactive AS (SELECT m.id old_id,m.code old_code,m.name old_name,COUNT(r.id) total_old FROM markets m JOIN result_draws r ON r.market_id=m.id WHERE COALESCE(m.is_active,FALSE)=FALSE GROUP BY m.id,m.code,m.name HAVING COUNT(r.id)>=1000), cand AS (SELECT *, CASE WHEN old_code='sgp-singapore' THEN 'singapore' WHEN old_code='chinapools' THEN 'china' WHEN old_code='magnum-cambodia' THEN 'cambodia' WHEN old_code='hongkong-lotto' THEN 'hongkong' WHEN old_code='sydney-lotto' THEN 'sydney' WHEN old_code LIKE 'toto-macau-%' THEN replace(old_code,'toto-macau-','totomacau-') WHEN old_code LIKE 'new-york-%' THEN replace(old_code,'new-york-','newyork-') WHEN old_code LIKE 'new-jersey-%' THEN replace(old_code,'new-jersey-','newjersey-') WHEN old_code LIKE 'north-carolina-%' THEN replace(old_code,'north-carolina-','carolina-') WHEN old_code LIKE 'washington-dc-%' THEN replace(old_code,'washington-dc-','washington-') ELSE old_code END AS step1_code FROM inactive), cand2 AS (SELECT *, replace(replace(replace(step1_code,'-evening','-eve'),'-midday','-mid'),'-morning','-mor') AS candidate_active_code FROM cand), resolved AS (SELECT c.*, m.id new_id,m.code new_code,m.name new_name FROM cand2 c JOIN markets m ON m.code=c.candidate_active_code AND m.is_active=TRUE) SELECT old_code,new_code,total_old,COUNT(o.id) FILTER (WHERE n.id IS NULL) AS missing_to_insert,COUNT(o.id) FILTER (WHERE n.id IS NOT NULL AND n.result=o.result) AS overlap_same,COUNT(o.id) FILTER (WHERE n.id IS NOT NULL AND n.result IS DISTINCT FROM o.result) AS overlap_diff FROM resolved x JOIN result_draws o ON o.market_id=x.old_id AND o.result ~ '^[0-9]{4}$' LEFT JOIN result_draws n ON n.market_id=x.new_id AND n.draw_date=o.draw_date GROUP BY old_code,new_code,total_old ORDER BY missing_to_insert DESC,old_code;"
  echo
  echo "=== 3. ACTIVE <1000 YANG PUNYA CANDIDATE HISTORY INACTIVE ==="
  sudo -u postgres psql -d bbfs_production -c "WITH active_counts AS (SELECT m.id,m.code,m.name,COUNT(r.id) active_total,MIN(r.draw_date) active_awal,MAX(r.draw_date) active_akhir FROM markets m LEFT JOIN result_draws r ON r.market_id=m.id WHERE m.is_active=TRUE GROUP BY m.id,m.code,m.name HAVING COUNT(r.id)<1000), inactive AS (SELECT m.id old_id,m.code old_code,m.name old_name,COUNT(r.id) old_total,MIN(r.draw_date) old_awal,MAX(r.draw_date) old_akhir FROM markets m JOIN result_draws r ON r.market_id=m.id WHERE COALESCE(m.is_active,FALSE)=FALSE GROUP BY m.id,m.code,m.name HAVING COUNT(r.id)>=1000), cand AS (SELECT *, CASE WHEN old_code='sgp-singapore' THEN 'singapore' WHEN old_code='chinapools' THEN 'china' WHEN old_code='magnum-cambodia' THEN 'cambodia' WHEN old_code='hongkong-lotto' THEN 'hongkong' WHEN old_code='sydney-lotto' THEN 'sydney' WHEN old_code LIKE 'toto-macau-%' THEN replace(old_code,'toto-macau-','totomacau-') WHEN old_code LIKE 'new-york-%' THEN replace(old_code,'new-york-','newyork-') WHEN old_code LIKE 'new-jersey-%' THEN replace(old_code,'new-jersey-','newjersey-') WHEN old_code LIKE 'north-carolina-%' THEN replace(old_code,'north-carolina-','carolina-') WHEN old_code LIKE 'washington-dc-%' THEN replace(old_code,'washington-dc-','washington-') ELSE old_code END AS step1_code FROM inactive), cand2 AS (SELECT *, replace(replace(replace(step1_code,'-evening','-eve'),'-midday','-mid'),'-morning','-mor') AS candidate_active_code FROM cand) SELECT a.code active_code,a.name active_name,a.active_total,a.active_awal,a.active_akhir,c.old_code,c.old_name,c.old_total,c.old_awal,c.old_akhir FROM active_counts a JOIN cand2 c ON c.candidate_active_code=a.code ORDER BY a.active_total,a.code;"
  echo
  echo "=== 4. CANDIDATE INACTIVE 1000+ TANPA MATCH AKTIF ==="
  sudo -u postgres psql -d bbfs_production -c "WITH inactive AS (SELECT m.id old_id,m.code old_code,m.name old_name,COUNT(r.id) total_old,MIN(r.draw_date) old_awal,MAX(r.draw_date) old_akhir FROM markets m JOIN result_draws r ON r.market_id=m.id WHERE COALESCE(m.is_active,FALSE)=FALSE GROUP BY m.id,m.code,m.name HAVING COUNT(r.id)>=1000), cand AS (SELECT *, CASE WHEN old_code='sgp-singapore' THEN 'singapore' WHEN old_code='chinapools' THEN 'china' WHEN old_code='magnum-cambodia' THEN 'cambodia' WHEN old_code='hongkong-lotto' THEN 'hongkong' WHEN old_code='sydney-lotto' THEN 'sydney' WHEN old_code LIKE 'toto-macau-%' THEN replace(old_code,'toto-macau-','totomacau-') WHEN old_code LIKE 'new-york-%' THEN replace(old_code,'new-york-','newyork-') WHEN old_code LIKE 'new-jersey-%' THEN replace(old_code,'new-jersey-','newjersey-') WHEN old_code LIKE 'north-carolina-%' THEN replace(old_code,'north-carolina-','carolina-') WHEN old_code LIKE 'washington-dc-%' THEN replace(old_code,'washington-dc-','washington-') ELSE old_code END AS step1_code FROM inactive), cand2 AS (SELECT *, replace(replace(replace(step1_code,'-evening','-eve'),'-midday','-mid'),'-morning','-mor') AS candidate_active_code FROM cand) SELECT c.old_code,c.old_name,c.total_old,c.old_awal,c.old_akhir,c.candidate_active_code FROM cand2 c LEFT JOIN markets m ON m.code=c.candidate_active_code AND m.is_active=TRUE WHERE m.id IS NULL ORDER BY c.total_old DESC,c.old_code;"
} > "$REPORT_FILE" 2>&1
cat "$REPORT_FILE"
bbfs-push-github || true
echo
echo "REPORT_PUSHED_TO_GITHUB=reports/audit_inactive_to_active_mapping.txt"
